# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

includes:
  git:
    taskfile: ~/.config/taskfile/git.yaml
    flatten: true

tasks:
  default:
    cmds:
      - task: pre
